language: python
python:
  - '3.6'
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - "flake8 ."
jobs:
  include:
    #- stage: test
    - stage: deploy
      if: branch IN (develop, beta, stable, master, enhancement/add-badges-update-version)
      script:
        - VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./scripts/calculate_version.sh)
        - echo "Version $VERSION"
        - bash ./scripts/build.sh $VERSION $TRAVIS_BRANCH
        - export OS=`uname -s`-`uname -m`
        - export EXECUTABLE_NAME=skale-$VERSION-$OS
      before_deploy:
        # Set up git user name and tag this commit
        - (
          test ! $TRAVIS_TAG &&
          git config --local user.name "skale-travis" &&
          git config --local user.email "$GITHUB_EMAIL" &&
          export TRAVIS_TAG=$VERSION &&
          git tag "$TRAVIS_TAG" &&
          git push https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG
          ) || true
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          name: $TRAVIS_TAG
          file:
            - dist/$EXECUTABLE_NAME
          on:
            repo: $TRAVIS_REPO_SLUG
            branch: stable
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          prerelease: true
          name: Build $(date +'%d.%m.%Y %R') - $TRAVIS_TAG
          file:
            - dist/$EXECUTABLE_NAME
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - master
              - develop
              - beta
              - enhancement/add-badges-update-version
        - provider: script
          skip_cleanup: true
          script: bash $TRAVIS_BUILD_DIR/scripts/upload_to_do.sh
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - master
              - stable
              - develop
              - beta